// Generated by CoffeeScript 1.8.0

/*
fastq-join.coffee
(Based on Fastq-join 1.01 by Expression Analysis / Erik Aronesty)

Copyright (c) 2015 Jeongbin Park

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */

import { jbfilereadersync } from "./jbfilereader";

var comp, dev, hd, joins, max, min, revcomp, run_fastq_join, _fq, _line,
  __modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

dev = 0;

joins = [];

_line = (function() {
  function _line() {
    this.s = '';
    this.n = 0;
  }

  return _line;

})();

_fq = (function() {
  function _fq() {
    this.id = new _line;
    this.seq = new _line;
    this.com = new _line;
    this.qual = new _line;
  }

  return _fq;

})();

comp = function(l) {
  var i, _i, _ref;
  for (i = _i = 0, _ref = l.length; _i < _ref; i = _i += 1) {
    if (l[i] === 'A') {
      l[i] = 'T';
    } else if (l[i] === 'T') {
      l[i] = 'A';
    } else if (l[i] === 'G') {
      l[i] = 'C';
    } else if (l[i] === 'C') {
      l[i] = 'G';
    } else if (l[i] === 'a') {
      l[i] = 't';
    } else if (l[i] === 't') {
      l[i] = 'a';
    } else if (l[i] === 'g') {
      l[i] = 'c';
    } else if (l[i] === 'c') {
      l[i] = 'g';
    }
  }
  return l;
};

revcomp = function(fq) {
  fq.seq.s = comp(fq.seq.s).reverse();
  fq.qual.s = fq.qual.s.reverse();
  return fq;
};

min = function(a, b) {
  if (a > b) {
    return b;
  } else {
    return a;
  }
};

max = function(a, b) {
  if (a < b) {
    return b;
  } else {
    return a;
  }
};

hd = function(a, s, b, n) {
  var d, i;
  d = 0;
  i = 0;
  while (n > 0) {
    if (a[s + i] !== b[i]) {
      d++;
    }
    n--;
    i++;
  }
  return d + n;
};

run_fastq_join = function(files, pgcallback, chunkcallback, reverse, mino, pctdiff) {
  var besto, bestscore, d, entries, fq, gzipped, i, li, maxo, mind, nfin, nrec, prevfpos, rc, read_fq, readers, ri, rtn, score, steprec, _i, _j, _k, rd1, rd2;
  if (mino == null) {
    mino = 6;
  }
  if (pctdiff == null) {
    pctdiff = 8;
  }
  dev = 0;
  joins = [];
  fq = [new _fq, new _fq];
  nrec = 0;
  prevfpos = 0;
  steprec = 500;
  readers = [0, 0];
  for (nfin = _i = 0; _i <= 1; nfin = _i += 1) {
    entries = files[nfin].name.split('.');
    if (entries[entries.length - 1] === 'gz') {
      gzipped = 1;
    } else {
      gzipped = 0;
    }
    readers[nfin] = new jbfilereadersync(files[nfin], gzipped);
  }
  read_fq = function() {
    var e, eofs, line, type, _j, _k;
    eofs = [false, false];
    for (nfin = _j = 0; _j <= 1; nfin = _j += 1) {
      for (type = _k = 0; _k <= 3; type = _k += 1) {
        try {
          line = readers[nfin].readline();
          if (line === "") {
            eofs[nfin] = true;
            break;
          }
        } catch (_error) {
          e = _error;
          self.postMessage({
            msgtype: 1,
            error: e
          });
          return 2;
        }
        if (type === 0) {
          fq[nfin].id.s = line.split("");
          fq[nfin].id.n = fq[nfin].id.s.length;
        } else if (type === 1) {
          fq[nfin].seq.s = line.split("");
          fq[nfin].seq.n = fq[nfin].seq.s.length;
        } else if (type === 2) {
          fq[nfin].com.s = line.split("");
          fq[nfin].com.n = fq[nfin].com.s.length;
        } else if (type === 3) {
          fq[nfin].qual.s = line.split("");
          fq[nfin].qual.n = fq[nfin].qual.s.length;
        }
      }
      if (fq[nfin].id.n === 0 || (fq[nfin].id.n !== 0 && fq[nfin].id.s[0] !== '@')) {
        self.postMessage({
          msgtype: 1,
          error: "Input file is not FASTQ!"
        });
        return 2;
      }
    }
    if ((eofs[0] === true && eofs[1] === false) || (eofs[0] === false && eofs[1] === true)) {
      self.postMessage({
        msgtype: 1,
        error: "# of rows in mate file doesn't match primary file!"
      });
      return 2;
    } else if (eofs[0] === true && eofs[1] === true) {
      return 1;
    } else {
      return 0;
    }
  };
  while (true) {
    nrec++;
    rtn = read_fq();
    if (rtn === 1) {
      break;
    } else if (rtn === 2) {
      return;
    }
    rc = revcomp(fq[1]);
    if (reverse) {
      rd1 = rc;
      rd2 = fq[0];
    } else {
      rd1 = fq[0];
      rd2 = rc;
    }
    maxo = min(rd1.seq.n, rd2.seq.n);
    bestscore = 2147483647;
    besto = -1;
    for (i = _j = mino; _j <= maxo; i = _j += 1) {
      mind = Math.floor((pctdiff * i) / 100);
      d = hd(rd1.seq.s, rd1.seq.n - i, rd2.seq.s, i);
      if (d <= mind) {
        score = Math.floor((1000 * (d * d + 1)) / i);
        if (score < bestscore) {
          bestscore = score;
          besto = i;
        }
      }
    }
    if (besto > 0) {
      for (i = _k = 0; _k < besto; i = _k += 1) {
        li = rd1.seq.n - besto + i;
        ri = i;
        if (rd1.seq.s[li] === rd2.seq.s[ri]) {
          //rd1.qual.s[li] = String.fromCharCode(max(rd1.qual.s[li].charCodeAt(0), rd2.qual.s[ri].charCodeAt(0)));
        } else {
          if (rd1.qual.s[li].charCodeAt(0) > rd2.qual.s[ri].charCodeAt(0)) {
            //rd1.qual.s[li] = String.fromCharCode(33 + min(rd1.qual.s[li].charCodeAt(0), max(rd1.qual.s[li].charCodeAt(0) - rd2.qual.s[ri].charCodeAt(0), 3)));
          } else {
            rd1.seq.s[li] = rd2.seq.s[ri];
            //rd1.qual.s[li] = String.fromCharCode(33 + min(rd2.qual.s[ri].charCodeAt(0), max(rd2.qual.s[ri].charCodeAt(0) - rd1.qual.s[li].charCodeAt(0), 3)));
          }
        }
      }
      joins.push(rd1.seq.s.join("") + rd2.seq.s.slice(besto).join(""));
    }
    if (__modulo(nrec, steprec) === 0) {
      if (prevfpos !== readers[0].fpos) {
        var progress = readers[0].fpos * 100 / files[0].size;
        if (progress > 99) {
          progress = 99;
        }
        pgcallback(progress);
        chunkcallback(joins);
        joins = [];
        prevfpos = readers[0].fpos;
      }
    }
  }
  chunkcallback(joins);
  pgcallback(100);
};

export { run_fastq_join };